language: objective-c
osx_image: xcode8.3
xcode_project: Game On.xcodeproj
xcode_scheme: Game On iOS
xcode_sdk: iphonesimulator10.3
before_install:
  - brew update
  - brew outdated carthage || brew upgrade carthage
  - carthage update
  - curl -O https://origincache.facebook.com/developers/resources/?id=facebook-ios-sdk-current.zip && unzip -o ?id=facebook-ios-sdk-current.zip -d Carthage/Build/iOS/ && rm ?id=facebook-ios-sdk-current.zip
  - carthage update
